Blog Post - English <Path to Industry 4.0>
tvarit-foggy/tvarit.com pull request #498
Opened 2020-12-09 11:01 UTC by shripaprikar

Added New Blog Post - English <Path to Industry 4.0>, under Gas & Oil Category... Used existing image, we can update image later once received

2020-12-09 11:27 UTC, Sumeshks29 requested changes

2020-12-09 11:27 UTC, Sumeshks29 commented on blogs/index.php
> +                                        Oil & Gas
@shripaprikar This blog shouldn't come under Oil and Gas Section, please confirm with @Poorvasisodia. Also any new blog must be on top, unless the marketing team has asked specifically to put it in the bottom.

@Poorvasisodia Please provide a relevant image.

2020-12-09 11:27 UTC, Sumeshks29 commented on blogs/best-practices-to-follow-for-data-science-projects-in-manufacturing-industry.php
> +</html>
@shripaprikar please add an empty line in the end.

2020-12-09 11:52 UTC, shripaprikar commented on blogs/index.php
> +                                        Oil & Gas
Category has been already changed in index page, its not under oil & gas

2020-12-09 11:54 UTC, shripaprikar commented on blogs/best-practices-to-follow-for-data-science-projects-in-manufacturing-industry.php
> +</html>
Do you mean to remove the empty line? Or need to add after HTML tag?

2020-12-09 11:57 UTC, shripaprikar commented on blogs/index.php
> +                                        Oil & Gas
Added under Group : Data scientists, CDO.

2020-12-09 12:10 UTC, Sumeshks29 commented on blogs/best-practices-to-follow-for-data-science-projects-in-manufacturing-industry.php
> +</html>
you need to add one extra empty line and html tag

2020-12-09 12:12 UTC, Sumeshks29 commented on blogs/index.php
> +                                        Oil & Gas
@shripaprikar what about the image?

2020-12-09 12:15 UTC, shripaprikar commented on blogs/index.php
> +                                        Oil & Gas
I am waiting for image... still waiting for that

2020-12-09 12:15 UTC, shripaprikar commented on blogs/best-practices-to-follow-for-data-science-projects-in-manufacturing-industry.php
> +</html>
Added Extra line space

2020-12-09 12:15 UTC, Poorvasisodia commented
> Added New Blog Post - English <Path to Industry 4.0>, under Gas & Oil Category... Used existing image, we can update image later once received

@shripaprikar I have shared the image yesterday.

2020-12-09 12:18 UTC, Poorvasisodia commented on blogs/index.php
> +                                        Oil & Gas
@shripaprikar I have shared the relevant image yesterday. Please check

2020-12-09 12:18 UTC, shripaprikar commented on blogs/index.php
> +                                        Oil & Gas
Used existing image

2020-12-09 12:22 UTC, Sumeshks29 commented on blogs/index.php
> +                                        Oil & Gas
![futuristic-industry-4-0-engineering-concept (1)](https://user-images.githubusercontent.com/35956666/101629335-3323b800-3a47-11eb-98c9-51ebf1ed2eb5.jpg)
Please compress this image to the lowest size possible and use it.

2020-12-10 06:24 UTC, Sumeshks29 approved these changes

2020-12-10 06:24 UTC, merged